@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YjBiMGViNmJiMDhiYjI4YmQ4ZGY4OSIsImlhdCI6MTc3NjI3NTEyOCwiZXhwIjoxNzc2Mjc2MzI4fQ.POWKm7id59JbNR4bjk_oai6EKPupW0kEAhnjX0rz4EM
GET http://localhost:5005/v1 
###
POST http://localhost:5005/v1/auth/register
Content-Type: application/json

{
    "first_name":"testF",
    "last_name":"testL",
    "email":"123@mail.com",
    "password":"123password123"
}
###
POST http://localhost:5005/v1/auth/login
Content-Type: application/json

{
    "first_name":"testF",
    "last_name":"testL",
    "email":"123@mail.com",
    "password":"123password123"
}
###
GET http://localhost:5005/v1/user
Authorization: Bearer token

###
POST http://localhost:5005/v1/jobs/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YjBiMGViNmJiMDhiYjI4YmQ4ZGY4OSIsImlhdCI6MTc3NTkyNDI3MiwiZXhwIjoxNzc1OTI1NDcyfQ.ueemzEG1iAKMU8FDXo17f0GQFw-VlJ-4qroLbgPZpgk
Content-Type: application/json

{
    "title":"test job",
    "positions":{"intern":0,"full-time":50}
}
###
POST http://localhost:5005/v1/jobs/add-contractor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YjBiMGViNmJiMDhiYjI4YmQ4ZGY4OSIsImlhdCI6MTc3NTkyNTk2MSwiZXhwIjoxNzc1OTI3MTYxfQ.YkzrfSqnx9hjacgS_4spkpUCBbCtrJIAzhxCWRy8syI
Content-Type: application/json

{
    "jobId":"69da7856b460bf5420e105a4",
    "position":"intern"
}
###
POST http://localhost:5005/v1/jobs/create-form
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "fields":[{"id":"q1","type":"text","label":"Quetion 1","required":false}]
}
###
POST http://localhost:5005/v1/jobs/respond-form
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "formId":"69dfcc13bdefe5d4298abebe",
    "hoursWorked": 2,
    "answers":{"q1":"text"}
}